### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'add'

### ISSUE THREAD

**Issue by ezgitas** [micom-dev/paper#6]
Hi,

The pipeline cannot run with the latest version of micom. 

`No parameters matching '_test' found
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       build_models
        1       elasticities
        1       elasticity_figures
        1       exchange_figures
        1       knockout_figures
        1       knockouts
        1       media_and_rates
        1       rate_figures
        1       tradeoff
        10
Select jobs to execute...

[Mon Mar 15 10:56:04 2021]
rule build_models:
    input: data/genera.csv, data/western_diet.csv
    output: data/models
    jobid: 2
    threads: 16

Traceback (most recent call last):
  File "/home/ezgi/paper/.snakemake/scripts/tmp96hiksdn.build_models.py", line 15, in <module>
    logger.add("micom.log")
AttributeError: 'Logger' object has no attribute 'add'
[Mon Mar 15 10:56:11 2021]
Error in rule build_models:
    jobid: 2
    output: data/models

RuleException:
CalledProcessError in line 29 of /home/ezgi/paper/Snakefile:
Command 'set -euo pipefail;  /home/ezgi/anaconda3/envs/micom/bin/python3.6 /home/ezgi/paper/.snakemake/scripts/tmp96hiksdn.build_models.py' returned non-zero exit status 1.
  File "/home/ezgi/anaconda3/envs/micom/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2347, in run_wrapper
  File "/home/ezgi/paper/Snakefile", line 29, in __rule_build_models
  File "/home/ezgi/anaconda3/envs/micom/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ezgi/anaconda3/envs/micom/lib/python3.6/concurrent/futures/thread.py", line 56, in run
  File "/home/ezgi/anaconda3/envs/micom/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ezgi/anaconda3/envs/micom/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2359, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ezgi/paper/.snakemake/log/2021-03-15T105601.352702.snakemake.log`

**Comment by cdiener** [comment]
Sorry for that. The logging interface recently changed in micom. It should work now when you update this repo.
